#pragma once

#ifdef BOOP_USE_ABC_NAMESPACE
#define BOOP_HEADER_START ABC_NAMESPACE_CXX_HEADER_START
#define BOOP_HEADER_END ABC_NAMESPACE_CXX_HEADER_END
#define BOOP_C_HEADER_START ABC_NAMESPACE_HEADER_START
#define BOOP_C_HEADER_END ABC_NAMESPACE_HEADER_END
#define BOOP_IMPL_START ABC_NAMESPACE_IMPL_START
#define BOOP_IMPL_END ABC_NAMESPACE_IMPL_END
#define BOOP_C_IMPL_START ABC_NAMESPACE_IMPL_START
#define BOOP_C_IMPL_END ABC_NAMESPACE_IMPL_END
#else
#define BOOP_HEADER_START
#define BOOP_HEADER_END
#ifdef __cplusplus
#define BOOP_C_HEADER_START extern "C" {
#define BOOP_C_HEADER_END }
#else
#define BOOP_C_HEADER_START
#define BOOP_C_HEADER_END
#endif
#define BOOP_IMPL_START
#define BOOP_IMPL_END
#define BOOP_C_IMPL_START
#define BOOP_C_IMPL_END
#endif
